// Generated by Sprocket. This file is overwritten each time Sprocket is run. Do not edit!

#include <AuthorizedRole.h>

module Spkt_GoverningRolesC {
    provides interface GoverningRoles;
}
implementation {

%GOVERNINGROLES%

    command int GoverningRoles.get_role_id(
        uint16_t component_identifier, uint8_t interface_identifier )
    {
        int i;
        
        for( i = 0; i < sizeof( authorized_roles ) / sizeof( struct AuthorizedRole ); ++i ) {
            if( authorized_roles[i].component_identifier == component_identifier &&
                authorized_roles[i].interface_identifier == interface_identifier ) {
                return authorized_roles[i].role_id;
            }
        }
        return -1;
    }

}
