// Generated by Sprocket. This file is overwritten each time Sprocket is run. Do not edit!

#include "CertificateStorage.h"

module Spkt_CertificatesC {
    provides interface CertificateStorage;
}
implementation {

%CERTIFICATES%

    command int CertificateStorage.certificate_count( )
    {
        return sizeof( certificates ) / sizeof( struct StoredCertificate );
    }
    
    
    command const struct StoredCertificate *CertificateStorage.get_storage( )
    {
        return certificates;
    }

}
